# Generated by Django 5.1.3 on 2024-11-09 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMarka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=20)),
                ('marka_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carmarka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=15)),
                ('millage', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('volume', models.DecimalField(decimal_places=1, max_digits=20)),
                ('have', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='vid/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('marka_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carmarka')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carmodel')),
            ],
        ),
    ]
