# Generated by Django 5.1.3 on 2024-11-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='car_name_tr',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_ru',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='color_tr',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='millage',
            field=models.FloatField(),
        ),
    ]
